import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Providers from "./provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "react-toastify/dist/ReactToastify.css";

const OpenSans = Open_Sans({
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["italic", "normal"],
  fallback: ["Helvetica Neue", "sans-serif"],
  subsets: ["latin-ext", "latin"],
});

export const metadata: Metadata = {
  title: "Aerozonix | Monitoring System Air Quality",
  description: "Generated by Developer Frozetero",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Providers>
          <ReactQueryDevtools
            initialIsOpen={false}
            buttonPosition="bottom-left"
          />

          {children}
        </Providers>
        <ToastContainer autoClose={2000} />
      </body>
    </html>
  );
}
